sudo: false
dist: xenial
language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION update "test:runMain ustcrv.Main" "runMain ustcrv.Main"

cache:
  directories:
    - target
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete

branches:
  only:
    - master
