version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch
    environment:
      JEKYLL_ENV: development
      LC_ALL: C.UTF-8
    branches:
      only: pages-source
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundler-{{ .Branch }}
            - bundler-pages-source
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - save_cache:
          key: bundler-{{ .Branch }}-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
            - ~/.bundle
      - run: bash .circleci/prepare.sh
      - run: bundle exec jekyll build
      - run: bash .circleci/patch.sh
      - run: bash .circleci/deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - build:
          branches:
            only:
              - pages-source
