name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Cache Artifacts
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-target-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-target-
    - name: SBT
      run: sbt update "test:runMain ustcrv.Main" "runMain ustcrv.Main"
    - name: Pre-cache cleanup
      run: |
        rm -fv $HOME/.ivy2/.sbt.ivy.lock
        find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
        find $HOME/.sbt -name "*.lock" -print -delete
        find target \( -name "*.json" -o -name "*.fir" -o -name "*.v" \) -print -delete
        true
